version: '3.8'
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    container_name: ubuntu-dotfiles
    volumes:
      - ./:/home/ubuntu
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    networks:
      - ubuntu-dotfiles

networks:
  ubuntu-dotfiles:
    driver: bridge
