version: '3.8'
services:
  ubuntu:
    build:
      context: ./coder/build
      dockerfile: Dockerfile
    privileged: true
    container_name: ubuntu-dotfiles
    volumes:
      - ./setup.sh:/home/ubuntu/setup.sh
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    networks:
      - ubuntu-dotfiles

networks:
  ubuntu-dotfiles:
    driver: bridge
